- src/lib.rs
Do not return a list of domains from get_provider_info (this was unused anyway)
> Do not return a list of domains from get_provider_info

- _providers/autistici.org.md
- _providers/old/autistici.org.md
Needs to be re-added. It seemed to always work OK. I found the server parameters at https://www.autistici.org/docs/mail/connectionparms
> re-added autistici.org

- _providers/mailo.com
closes #89 
tested it out. I had to guess the servers, but even entering them manually works. They seem to show to the same server for now. Should be backwards-compatible even if they expand their infrastructure.
> added mailo.com

- README.md
it was a bit unclear to me (or i forgot it),
what happens when no servers are defined.
i suspected, that in this case, autoconfig/autodiscover are skipped -
which may have led to a worsening when for a provider a provider-entry is defined.
however, in fact, this is not the case.
the rust-core does not differ between missing provider-entries
or provider-entries without servers -
get_offline_autoconfig() just returns None in both cases.
for accessing additional information from a provider-entry,
there is an additional function, get_provider_info()
targets #113
> clarify what happens when no servers are defined

- _providers/nauta.cu.md
cc @adbenitez 
later, in another pr, we can also enable `delete_server_after`, maybe it is a good idea, not sure. but in any case, i would give server-autodeletion a bit more time to be opt-in tested.
> some nauta.cu config-defaults

- README.md
- _providers/gmail.md
- _providers/yandex.ru.md
the idea of this pr is to use the provider-db as a whitelist and a blacklist for domains supporting some oauth2-providers:
- if the line `oauth2 = yandex | gmail` is present for a provider/domain, we know, that oauth2 is supported
- if no `oauth2` line is present, we know that oauth2 is not supported and **we can skip the mx-lookup**, which may also consume some time, see https://github.com/deltachat/deltachat-android/issues/1426 and is not needed in most cases.
apart from that, the code at https://github.com/deltachat/deltachat-core-rust/blob/master/src/oauth2.rs#L273 can be streamlined and it is no longer needed to maintain a whiltelist of domains there - and to keep it in sync with the provider-db.
morever, this pr syncs the list of domains between oauth2.rs and provider.db - maybe a …
> Mark oauth2 providers as such

- _providers/five.chat.md
New list can be retrieved by HTTPS, and all these ports can be guessed
if HTTPS fails.
> Remove outdated five.chat server list.

- _providers/nauta.cu.md
'fetch_existing' will be renamed to 'fetch_existing_msgs', see https://github.com/deltachat/deltachat-core-rust/pull/2042 - current default is `0`, however, that may change and for nauta we will probably keep skeptical on this option.
> adapt to rename of 'fetch_existing'

- _providers/nauta.cu.md
with https://github.com/deltachat/deltachat-core-rust/pull/2121, all providers from the provider-db will use get strict_tls=true as a default setting, this pr changes keeps strict_tls=false explicitly for nauta.
all other providers in the provider-db should be able to handle strict_tls=true as this is the new default.
> disable strict_tls explicitly for nauta

- _providers/example.com.md
It is specified in RFC 2606 along with example.com and example.org.
> Add example.net

- _providers/gmail.md
I have no Google account to try, but GSuite (Google Workspace) uses
ASPMX.L.GOOGLE.COM. in MX records so this will be needed if provider is
identified via MX lookup.
This is what Thunderbird does, too:
https://autoconfig.thunderbird.net/v1.1/google.com
> Add google.com to the list of Gmail domains

- _providers/fastmail.md
fastmail.com has ports 143, 465, 587 and 993 filtered,
causing a timeout on the client before the correct server is tried.
Specifying the server list speeds up configuration in this case.
> fastmail: add "server" section

- _providers/fastmail.md
Took me a while to figure this out, but if you log in with an email based on a custom domain, Delta Chat will time out as it will not find the correct servers and ports.
> Warn about Fastmail custom domain configuration

- _providers/posteo.md
Somehow the domain `posteo.it` has not been included, but it does exist, according to [this Posteo support article](https://posteo.de/en/help/which-domains-are-available-to-use-as-a-posteo-alias-address).
> Add domain posteo.it for use in email address

- README.md
it is supported by deltachat-core-rust as of
https://github.com/deltachat/deltachat-core-rust/pull/2604
and used eg. by
https://github.com/deltachat/provider-db/pull/195
> document `socket: PLAIN`

- _providers/fastmail.md
While creating test accounts, I found out that the steps have been slightly reworded. So I changed the description:
> app password generation process has changed for fastmail

- _providers/gmail.md
IMAP was not enabled on my test, not sure what the default is/was over time and how that relates to oauth2, but adding a hint is probably useful
> update gmail html hints

- _providers/infomaniak.com.md
This was found out during tests with github.com/deltachat/eppdperf.
We don't know if paid accounts support more recipients; but as they usually come with a domain of their own, we don't need to distinguish them extra.
> free infomaniak accounts support max. 10 recipients

- _providers/dubby.org.md
- _providers/five.chat.md
- _providers/nauta.cu.md
- _providers/testrun.md
that is no longer needed since
https://github.com/deltachat/deltachat-core-rust/pull/2906 -
just use mvbox_move.
> remove mvbox_watch config default

- _providers/fastmail.md
Fastmail supports a ton of domains that a user can pick during sign up that don't have their own IMAP or SMTP gateways. This requires using the Advanced setup as part of the "common" use case.
The app-specific password generation combined with the webmail email address as the "username" for authentication easily causes confusion for custom domains about which fields during setup are for the custom domain and which are for the gateway login names (especially the IMAP password).
> Fastmail.md setup Update

- _providers/aktivix.org.md
port 25 is also open, but STARTTLS is only available on port 587. the testscript from #223 confirms this. I don't have any source for this, as the SMTP settings for aktivix don't seem to be documented; this is probably how this error happened.
> aktivix.org: fixed port for STARTTLS

- _providers/yggmail.md
there's no a need to move messages to the delta chat folder for yggmail, as it is a per-device account and chat only. Moreover we're working around an yggmail bug that appearantly swallows messages during the move operation.
> Disable move to Delta Chat folder for yggmail

- _providers/hermes.radio.md
Here are all the sub-domains used by "hermes.radio" up to now (and other small change). Ideally all subdomains should be covered, by using a wildcard domain like "*.hermes.radio" or just automatically considering all possible prefixes of the listed domains.
> Rising the question of wildcard domain support (or something that gets the job done)

- _providers/ouvaton.coop.md
A co-operative run hosting provider in France that primarily operates in French and English
> Adding Ouvaton to providers list

- index.html
Added Delta Chat link, fixed a typo, added missing commas, used proper quotation marks and apostrophe,
clarified that "provider" is an "email provider".
"E-Mail" is replaced with "email" as it is more common and spelled on Wikipedia and Gmail pages this way.
> Improve static text on the index page

- .github/workflows/jekyll.yml
Use PR ID in the URL instead of the hash
and build without Docker.
Fixes #197
> ci: refine Jekyll preview workflow

- _providers/gmx.net.md
@gerryfrancis helped someone with a gmx account to log in to Delta Chat, and noticed that in the mobile version of the GMX website, in the settings, the button to turn on IMAP is missing... there is only "application specific passwords" to choose from, and those in turn only work with 2FA, which then doesn't work with Delta Chat either. The solution was to display the GMX website in the desktop version, where the checkbox is of course available.
I didn't test it since June, because on my laptop it simply works. Maybe someone with a smartphone can quickly check this before we merge this?
> GMX mobile settings don't show IMAP checkbox

- _providers/purelyemail.com.md
> added purelyemail.com

- _providers/rambler.ru.md
For the reviewer: please verify that the servers list makes sense. Maybe Delta Chat tries all those additional ones by itself and they don't need to be specified? What about `PLAIN`? Will Delta Chat make sure the ones with encryption?
Also FYI I haven't actually tested this data in action, nor have I tried to log in to my Rambler account with Delta Chat.
> add rambler.ru

- validation/index.js
currently many providers are failing
Current output:
```
Error in arcor.de.md:
Error Error in server definition:Unexpected key "username"
Error in blindzeln.org.md:
Error Error in server definition:Unexpected key "username"
Error in c1.testrun.org.md:
Error Error in server definition:Unexpected key "username"
Error in c2.testrun.org.md:
Error Error in server definition:Unexpected key "username"
Error in c3.testrun.org.md:
Error Error in server definition:Unexpected key "username"
Error in daleth.cafe.md:
Error Error in server definition:Invalid Socket "TLS"
Error in disroot.md:
Error Error in server definition:Unexpected key "username"
Error in e.email.md:
Error Error in server definition:Unexpected key "username"
Error in example.com.md:
Error Error in server definition:Unexpected key …
```
> add more validation for `server`

- _providers/arcor.de.md
- _providers/blindzeln.org.md
- _providers/c1.testrun.org.md
- _providers/c2.testrun.org.md
- _providers/c3.testrun.org.md
- _providers/daleth.cafe.md
- _providers/disroot.md
- _providers/e.email.md
- _providers/example.com.md
- _providers/fastmail.md
- _providers/infomaniak.com.md
- _providers/mail.com.md
- _providers/mail.de.md
- _providers/mailbox.org.md
- _providers/mehl.cloud.md
- _providers/mehl.store.md
- _providers/nine.testrun.org.md
- _providers/nubo.coop.md
- _providers/ouvaton.coop.md
- _providers/purelymail.com.md
- _providers/riseup.net.md
- _providers/systemausfall.org.md
- _providers/systemli.org.md
- validation/index.js
@WofWca I removed the empty server block in `mail.com.md` again (which was introduced in #287) - doesn't core try out common server names anyway? There are many providers without a server block, this is quite typical.
> Make validation pass again

- _providers/vk.com.md
I have verified it, it works. I can receive emails.
But their FAQ still states that vk.com can't work
with other email clients:
https://help.vk.mail.ru/vkmail/questions/client
Maybe they just haven't updated it yet?
Or maybe they're just testing and might disable it again, as it once happened:
https://vk.com/wall-104054395_14970?w=wall-104054395_14970_r15160
> change vk.com from BROKEN to PREPARATION

- _providers/gmail.md
i also added a small para for reasoning, trying to be mostly neutral :)
targets https://github.com/deltachat/deltachat-android/issues/3233
> adapt to removed gmail-oauth2

- README.md
Referenced to issue https://github.com/deltachat/deltachat-android/issues/3233 .
> Remove Gmail reference in regard to OAuth2 (and fix typos) in README.md

- _providers/icloud.md
Figured out how to use Custom Email Domain hosted on iCloud+. I'd like to update the description of iCloud provider to maybe save the next person some time.
I don't know if formatting lists the way I did works in provider description (or if this is even the right place to add this information) so please let me know if this is wrong.
> Update icloud.md for Custom Email Domain

- _providers/outlook.com.md
It seems that they are rolling out per-app-passwords so they are failing to login.
> Mark outlook as broken
