deltachat/provider-db

_providers/gmx.net.md
an outcome from https://github.com/deltachat/deltachat-android/issues/879
=> add hint about gmx folder limitations

assets/search.js, index.html, new.html
A page which shows a table optimized for people who want to create a new account for DC.
=> Show provider table for account creation

_providers/disroot.md
=> disroot can have long delays

assets/normalize.css, assets/styles.css, index.html
=> Style overhaul 2

_providers/ovh.it.md, _providers/tiscali.it.md
@andreaslattmann is this info correct? Do you just need your E-Mail password or do you need a special app password for Delta?
closes #46 
closes #47
=> added OVH and tiscali

README.md, _providers/aktivix.org.md, _providers/example.com.md, _providers/gmail.md, _providers/gmx.net.md, _providers/hotmail.md, _providers/icloud.md, _providers/web.de.md, _providers/yahoo.md
closes #63 
I changed state to status.
I also changed date to last_checked. ([discussion: https://github.com/deltachat/provider-db/pull/52#issuecomment-578218709](https://github.com/deltachat/provider-db/pull/52#issuecomment-578218709))
=> state -> status, date -> last_checked

.travis.yml
=> remove travis - there is no rust left in this repo.

assets/styles.css
They had been overwritten by the ones for the index page in #70
=> Fix styles of status sub-headlines.

_providers/hotmail.md
=> added after_login_hint for outlook & hotmail

assets/styles.css, fallback.html, index.html
Another #65 regression ;) The colors are missing:
Follow-Up PR to #70
=> trying to fix the status boxes on index

_providers/yahoo.md
before_login_hint is always requires on PREPARATION
=> add missing before_login_hint for yahoo

_providers/outlook.com.md
see https://en.wikipedia.org/wiki/Outlook.com
=> hotmail does not longer exists since 2012

README.md, _providers/t-online.md
add the missing `before_login_hint` to t-online, clarify the README for this aspect.
=> fix t-online

_providers/zoho.com.md
=> removed zoho (only custom domains)

.github/workflows/validation.yml, _providers/aol.md, _providers/ziggo.nl.md, validation/.gitignore, validation/index.js, validation/package-lock.json, validation/package.json
=> validation of data

_providers/protonmail.md, validation/index.js
=> tweak protonmail

_providers/aol.md
=> setup AOL with an App password

.github/ISSUE_TEMPLATE.md
=> issue template for new data structure

.github/workflows/jekyll.yml
re-try of #106 - this time with the correct code I guess.
=> post link to comments if not posted to details

_providers/chello.at.md
Reference: https://www.magenta.at/faq/#!technische+anfrage/kabelfestnetz+internet/email/frage/20590
Thanks!
=> Add chello.at to Delta Chat providers

_providers/disroot.md, _providers/five.chat.md, _providers/gmail.md, _providers/mailbox.org.md, _providers/posteo.md, _providers/riseup.net.md, _providers/systemli.org.md, _providers/testrun.md, _providers/yandex.ru.md
just a few for first tests ...
corresponding rust pr: https://github.com/deltachat/deltachat-core-rust/pull/1587
=> enable strict_tls for some providers

_providers/vodafone.de.md
Issue https://github.com/deltachat/provider-db/issues/129
=> Add Vodafone.de to Delta Chat providers

_providers/yandex.ru.md
source: https://autoconfig.yandex.com/mail/config-v1.1.xml
and https://github.com/deltachat/deltachat-android/issues/1526
=> add yandex server

_providers/buzon.uy.md, _providers/undernet.uy.md
=> add buzon.uy

_providers/firemail.de.md
=> add firemail.de

_providers/hermes.radio.md
Hi all. We are still setting up our email servers, but would like to start testing.
=> Added hermes.radio provider, a project by Rhizomatica Communications.

README.md, _providers/nauta.cu.md
successor of #149, now the setting is at the correct place :)
=> set max_smtp_rcpt_to for nauta

_providers/espiv.net.md
Espiv is an autonomous collective based in Greece providing emails among other radical services.
=> Add espiv.net.md

_providers/yandex.ru.md
closes #144.
I still left the russian link for people who don't speak english. They might appreciate it for now.
=> added more verbose english link

_providers/e.email
=> added e.email

.github/workflows/jekyll.yml
=> fix Gemfile lock permissions

_providers/i3.net.md
They provided us a test account, I tested it. Works flawlessly.
=> added i3.net as provider

_providers/freenet.de.md
(I accidentally pushed to master, instead of a new branch. As I can't force-push on master, I decided to just revert the commit, so master is as before again. Now I reverted the revert commit, which means that this PR contains the changes I wanted to make in the first place. Always think twice before doing git commands, children.)
I didn't test this myself. @angelo-fuchs you tested this, right? Would these instructions have helped your friend?
closes #139
=> Added freenet.de preparation instructions

_providers/outlook.com.md
- status is OK now as with
https://github.com/deltachat/deltachat-core-rust/issues/1006
we found a way to fix at least outlook.com+delta-to-delta communication
- server parameters updated, see
https://support.microsoft.com/en-us/office/pop-imap-and-smtp-settings-for-outlook-com-d088b986-291d-42b8-9564-9c414e2aa040
and login-settings (nice is that preparations are not needed btw!)
=> update outlook setting

_providers/mail.ru.md
@link2xt can you translate that sentence into russian? Otherwise we could also leave it in english...
closes #168
=> added english before_login_hint for mail.ru

_providers/tutanota.md
it is just copy+pasted from hey.com ...
closes #178
=> add Tutanota as BROKEN

_providers/zoho.md
Adds Zoho Mail to Delta Chat provider database.
=> Adds Zoho Mail to database

_providers/vivaldi.md
Adds Vivaldi Webmail to database
=> Adds Vivaldi Webmail to database

_providers/163.md, _providers/icloud.md, _providers/naver.md, _providers/qq.md
I misunderstood that 'before_login_hint' would appear at the database page. This PR supplements the content and simplifies 'before_login_hint'.
=> Added additional information to QQ.md, 163.md and naver.md.

_providers/mail.ru.md
Updates mail.ru to add server metadata
=> Updates mail.ru to add server metadata and internet.ru

_providers/i.ua.md
=> i.ua is broken.

_providers/yggmail.md
that should make configuration a bit easier :)
however, it should still be possible to use different ports.
=> add yggmail

README.md
alternative to https://github.com/deltachat/provider-db/pull/201, at least to me, this was not totally clear.
=> clarify strict_tls wrt PLAIN

_providers/protonmail.md
It's still broken of course, but now we can at least tell more people how broken it is. /s
source: https://pm.me/
=> pm.me is part of protonmail

_providers/infomaniak.com.md
I tried it myself, we have a test account now, it worked :)
closes #208
=> added @ik.me mail addresses. closes #208

_providers/posteo.md
Update of Posteo alias domains (according to https://posteo.de/en/help/which-domains-are-available-to-use-as-a-posteo-alias-address)
=> Posteo domain alias update

_providers/disroot.md, _providers/mailbox.org.md, _providers/riseup.net.md, _providers/systemli.org.md
=> added slow providers

_providers/mail.de.md
this morning it was still fine, but with updated core it doesn't run as smoothly. Anyway, this PR has the same rationale as #219.
superceedes #221.
=> added server data for mail.de

_providers/mail.ru.md, validation/index.js
closes #224 
@Yettte is the russian correct?
=> mail.ru: russian hint for setting an external app password

_providers/outlook.com.md
closes #225 
@sistein like this?
=> outlook.de is also a valid outlook domain

_providers/qq.md
the testscript in #223 produced an error, which led me to research the problem. this page shows that SSL would be correct, which is also backed by my testscript results :)
=> QQ: wrong encryption algorithm, tested with script

_providers/nauta.cu.md
situation changed, no need to sacrifice encryption anymore, old monthly email-only data plan changed from 50MB to 600MB!
=> update nauta.cu provider info

README.md
I'm looking for this information every single time^^ maybe this should also be documented in the core repository, don't know. Personally, I would look here first, that's why I opened the PR here.
Source: https://github.com/deltachat/deltachat-core-rust/pull/3399
=> documented import script

_providers/nubo.coop.md
A co-operative run email provider in Belgium that primarily operates in French and Flemish
=> Adding nubo.coop to providers list

_providers/sonic.md
Hi thought it might be helpful to add Sonic.
=> Added sonic.com, a popular ISP in California USA.

_providers/posteo.md
Should favour TLS connections.
=> Posteo: Move from STARTTLS to SSL socket

_providers/buzon.uy.md, _providers/disroot.md, _providers/espiv.net.md, _providers/five.chat.md, _providers/gmail.md, _providers/hermes.radio.md, _providers/infomaniak.com.md, _providers/mail2tor.md, _providers/mailbox.org.md, _providers/nauta.cu.md, _providers/nubo.coop.md, _providers/ouvaton.coop.md, _providers/posteo.md, _providers/riseup.net.md, _providers/systemli.org.md, _providers/testrun.md, _providers/undernet.uy.md, _providers/yandex.ru.md, validation/index.js
+ set `delete_to_trash` for Gmail.
=> Move strict_tls, max_smtp_rcpt_to to a new opt: section in *.md

.github/workflows/jekyll.yml
2nd try to view if comment appears correctly this time. supercedes #253
=> fix preview link after testrun.org migration

_providers/aliyun.md
Closes #180
I have not actually tested if it works though.
=> Add Alibaba Mail

_providers/acesttoi.fr, _providers/daleth.cafe.md, _providers/mehl.cloud.md
Some litte changes at my chatmail-instances....
=> Maybe now?

_providers/stinpriza.net.md
hey, 
please add stinpriza coop email hosting service. domains listed are only the ones stinpriza coop owns.
thx!
=> add stinpriza email hosting

_providers/icloud.md
=> update last_checked for iCloud

_providers/163.md
Hello, I'm very interested in this app and tried it with a newly created 163 account (while my other 126 accounts has no spare auth codes). It seems that your descriptions are out of date for the provider, so I updated it a little. I'm not very familiar with your guideline here, so adjust the wording as you like.
By the way, while the e-mail system is the only mature decentralized system and apt for the chat data communication, I'm really curious whether is there any way to directly chat between two clients without the server (which is really what p2p means), considering the complicated network factors like IPv4/NAT, proxy, firewall, ad-hoc wireless network connection and so on. Are there any progress for the mission impossible? Thanks.
=> Update Email Provider Database with the "163.com" entry
